In [54]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score
from sklearn.ensemble import RandomForestClassifier

In [10]:
# load the read the dataset
df = pd.read_csv('../data/processed/clean_data.csv')
df.head()

   District ConstituencyTitle  ... Turnout  Year
0  peshawar              NA-1  ...   28.73  2002
1  peshawar              NA-1  ...   22.97  2008
2  peshawar              NA-1  ...   46.18  2013
3   chitral              NA-1  ...   60.97  2018
4  peshawar              NA-2  ...   26.49  2002

[5 rows x 10 columns]

In [11]:
df.isnull().sum()

District                 0
ConstituencyTitle        0
WinningParty             0
Votes                    0
TotalValidVotes          0
TotalRejectedVotes       0
TotalVotes               0
TotalRegisteredVoters    0
Turnout                  0
Year                     0
dtype: int64

In [16]:
df.dtypes

District                  object
ConstituencyTitle         object
WinningParty              object
Votes                      int64
TotalValidVotes            int64
TotalRejectedVotes         int64
TotalVotes                 int64
TotalRegisteredVoters      int64
Turnout                  float64
Year                       int64
dtype: object

In [ ]:
# separate the categorical and numerical columns
num_col = df.select_dtypes(include = 'number')
cat_col = df.select_dtypes(include = 'object')
cat_col.columns

Index(['District', 'ConstituencyTitle', 'WinningParty'], dtype='object')

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
num_scale = scaler.fit_transform(num_col)
num_scale

array([[ 0.29163276, -0.61887791, -0.56455283, ..., -0.07701806,
        -1.30622638, -1.57409491],
       [-0.71853561, -0.32333933, -0.88809648, ...,  0.99891601,
        -1.73363685, -0.526931  ],
       [-0.7178262 ,  0.42712255, -0.37140814, ...,  0.53177367,
        -0.01138043,  0.3457056 ],
       ...,
       [-0.67739   , -0.62014173, -0.54597449, ...,  1.28107687,
        -1.2394435 , -0.526931  ],
       [-0.72246463,  0.93846176,  1.11591116, ...,  0.59279965,
         0.88128415,  0.3457056 ],
       [ 1.4962878 ,  1.22017649,  1.45978583, ...,  0.98693278,
         0.68464565,  1.2183422 ]], shape=(3700, 7))

In [37]:
num_scale_df = pd.DataFrame(num_scale, columns=num_col.columns)
df[num_col.columns] = num_scale_df

In [ ]:
# Converted the categorical columns into numerical
df['District_encoded'] = df['District'].map(df['District'].value_counts())
df['Constituency_encoded'] = df['ConstituencyTitle'].map(df['ConstituencyTitle'].value_counts())
df.drop(columns =['District','ConstituencyTitle'], inplace =True)

In [38]:
df.head(2)

               WinningParty     Votes  ...  District_encoded  Constituency_encoded
0  muttahidda majlis-e-amal  0.291633  ...                78                    23
1               independent -0.718536  ...                78                    23

[2 rows x 10 columns]

In [39]:
X = df.drop(columns = ['WinningParty'])
y = df['WinningParty']

In [42]:
# Split the data into train set and test set
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [47]:
# Checkout the Dimension
print("X_train", X_train.shape)
print("X_test", X_test.shape)
print("Y_train", y_train.shape)
print("Y_test", y_test.shape)

X_train (2960, 9)
X_test (740, 9)
Y_train (2960,)
Y_test (740,)

In [49]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [51]:
y_pred = model.predict(X_test)
print(accuracy_score(y_pred, y_test))

0.6067567567567568